### ISSUE TITLE
Merged image skipped the last dozens images in a folder

### ISSUE THREAD

**Issue by mobicu** [YofaGh/MangaScraper#5]
I tried to use python cli.py merge -folder "path_to_images_folder" -fit
It properly merged the first hundred or so images into two separate merged image but the last remaining images is not merged and merely left out. Can you help me with this?

**Comment by YofaGh** [comment]
Can you provide more details regarding this issue?

**Comment by mobicu** [comment]
Still the same without fit.  I have about 230 images in a folder so it basically merged the 170 images into 2 separate image. the last 60 images are not merged and just left out

**Comment by YofaGh** [comment]
Ok. I just tested it with a set of 800 images and it properly merged all of them into 22 images. I'm gonna need more information on this issue. maybe you can give me the images?
or if you have used the downloaders, give me the domain and the url/code to webtoon so I can test it myself

**Comment by mobicu** [comment]
Oh sorry i havent updated the mangascraper git. let me update and try again and i'll let you know soon enough

**Comment by mobicu** [comment]
I tried. This time all the images are merged but the image order is not proper yet. Btw for reference here's the chapter i want to be merged and the merged images result.
[Uploading Merged.zip…]()

**Comment by YofaGh** [comment]
I figured out the problem. your operating system sorts the images in a different way that image_merger.py sorts them.
the problem was the way you had named the images. but you don't need to rename them anymore because I handled the problem by using natsort module. Remember to fetch the code and run `pip install -r requirements.txt` or `pip install natsort`.
Btw I'm closing the issue:)

**Comment by mobicu** [comment]
Thanks. It works great now :) Amazing project btw. This is the first project that i know that does hundreds of image merge properly. Keep up the good work
