### ISSUE TITLE
SyntaxError: f-string: unmatched '('

### ISSUE THREAD

**Issue by mobicu** [YofaGh/MangaScraper#6]
D:\Github\Merge-image>python cli.py merge -folder "Merged\CH (1)" -fit
Traceback (most recent call last):
  File "D:\Github\Merge-image\cli.py", line 86, in <module>
    from utils.image_merger import merge_folder
  File "D:\Github\Merge-image\utils\image_merger.py", line 42
    copy2(list_to_merge[0].filename, f'{path_to_destination}/{index+1:03d}.{list_to_merge[0].filename.split('.')[-1]}')
                                                                                                             ^
SyntaxError: f-string: unmatched '('

**Comment by YofaGh** [comment]
Regarding this, as of python 3.12.0, f-strings support nested apostrophe characters. so please update your python to 3.12.x or higher
