### ISSUE TITLE
Comick not working

### ISSUE THREAD

**Issue by anotherduckling** [YofaGh/MangaScraper#7]
The main domain has changed. It is still using comick.cc.

**Comment by YofaGh** [comment]
I am aware of the changes. The domain has been changed to comick.io, and it appears that they have added Cloudflare to the website. I am currently investigating to see if there is anything I can do.

**Comment by YofaGh** [comment]
> The main domain has changed. It is still using comick.cc.

I am aware of the changes. The domain has been changed to comick.io, and it appears that they have added Cloudflare to the website. I am currently investigating to see if there is anything I can do.

**Comment by YofaGh** [comment]
> The main domain has changed. It is still using comick.cc.

It should be working now so I'll be closing this issue.
